In [2]:
import numpy as np
from scipy import linalg
from discreteMarkovChain import markovChain

In [84]:
P = np.array ([[0, 1/5, 1/5, 1/5, 1/5, 0, 1/5, 0],
               [1/5, 0, 1/5, 1/5, 0, 1/5, 0, 1/5],
               [1/5, 1/5, 0, 1/5, 0, 1/5, 1/5, 0],
               [1/5, 1/5, 1/5, 0, 1/5, 0, 0, 1/5],
               [1/4, 0, 0, 1/4, 0, 0, 1/4, 1/4],
               [0, 1/4, 1/4, 0, 0, 0, 1/4, 1/4],
               [1/4, 0, 1/4, 0, 1/4, 1/4, 0, 0],
               [0, 1/4, 0, 1/4, 1/4, 1/4, 0, 0]
    
])

In [112]:
#making V matrices

l = np.array([[0,1] , [2], [3], [4], [5], [6], [7]])
def get_v (loc_matrix):
    v = np.zeros((l.size, l.itemsize))
    for k in range(l.size):
        for o in l[k]:
            v[k][o] = 1.0
    v = v.T
    return v

get_v(l)

array([[1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [113]:
def get_u (v):
    u = np.linalg.inv(np.dot(v.T,v))
    u = u.dot(v.T)
    return u
get_u (get_v(l))

array([[0.5, 0.5, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. ]])

In [114]:
def get_Pnl (u, p, v):
    Pl = u.dot(p).dot(v)
    return Pl
P1 = get_Pnl(get_u (get_v(l)),P,get_v(l))

In [115]:
P1

array([[0.2 , 0.2 , 0.2 , 0.1 , 0.1 , 0.1 , 0.1 ],
       [0.4 , 0.  , 0.2 , 0.  , 0.2 , 0.2 , 0.  ],
       [0.4 , 0.2 , 0.  , 0.2 , 0.  , 0.  , 0.2 ],
       [0.25, 0.  , 0.25, 0.  , 0.  , 0.25, 0.25],
       [0.25, 0.25, 0.  , 0.  , 0.  , 0.25, 0.25],
       [0.25, 0.25, 0.  , 0.25, 0.25, 0.  , 0.  ],
       [0.25, 0.  , 0.25, 0.25, 0.25, 0.  , 0.  ]])

In [117]:
def normalize_stochastic_matrix (x):
    for i in range (int (np.sqrt(x.size))):
        k = 1 - x[i][i]
        x[i][i] = 0
        x[i]  =x[i]* ((k)**(-1))
    return x

P1n = normalize_stochastic_matrix(P1)

In [78]:
2/5

0.4

In [ ]:
def get_eigen_stationarydist(m):
    w, vl, vr = linalg.eig(m, left=True)
    mc = markovChain(m)
    mc.computePi('linear')
    return {'eigen values': w, 'eigen vector': vl,'stationary distribution': mc.pi}

get_eigen_stationarydist(P1n)