In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
a, b = 1/5, 1/4

In [72]:
m = np.array([[0, a, a, a, a, 0, a, 0],
              [a, 0, a, a, 0, a, 0, a],
              [a, a, 0, a, 0, a, a, 0],
              [a, a, a, 0, a, 0, 0, a],
              [b, 0, 0, b, 0, 0, b, b],
              [0, b, b, 0, 0, 0, b, b],
              [b, 0, b, 0, b, b, 0, 0],
              [0, b, 0, b, b, b, 0, 0]])

In [74]:
m

array([[0.  , 0.2 , 0.2 , 0.2 , 0.2 , 0.  , 0.2 , 0.  ],
       [0.2 , 0.  , 0.2 , 0.2 , 0.  , 0.2 , 0.  , 0.2 ],
       [0.2 , 0.2 , 0.  , 0.2 , 0.  , 0.2 , 0.2 , 0.  ],
       [0.2 , 0.2 , 0.2 , 0.  , 0.2 , 0.  , 0.  , 0.2 ],
       [0.25, 0.  , 0.  , 0.25, 0.  , 0.  , 0.25, 0.25],
       [0.  , 0.25, 0.25, 0.  , 0.  , 0.  , 0.25, 0.25],
       [0.25, 0.  , 0.25, 0.  , 0.25, 0.25, 0.  , 0.  ],
       [0.  , 0.25, 0.  , 0.25, 0.25, 0.25, 0.  , 0.  ]])

In [73]:
len(m)

8

get eigen vector

In [4]:
# normalize the matrix so that rows sum to 1

P = m/np.sum(m, 1)[:, np.newaxis]

In [5]:
P

array([[0.  , 0.2 , 0.2 , 0.2 , 0.2 , 0.  , 0.2 , 0.  ],
       [0.2 , 0.  , 0.2 , 0.2 , 0.  , 0.2 , 0.  , 0.2 ],
       [0.2 , 0.2 , 0.  , 0.2 , 0.  , 0.2 , 0.2 , 0.  ],
       [0.2 , 0.2 , 0.2 , 0.  , 0.2 , 0.  , 0.  , 0.2 ],
       [0.25, 0.  , 0.  , 0.25, 0.  , 0.  , 0.25, 0.25],
       [0.  , 0.25, 0.25, 0.  , 0.  , 0.  , 0.25, 0.25],
       [0.25, 0.  , 0.25, 0.  , 0.25, 0.25, 0.  , 0.  ],
       [0.  , 0.25, 0.  , 0.25, 0.25, 0.25, 0.  , 0.  ]])

In [6]:
eigenvalues, eigenvectors = np.linalg.eig(P.T)

In [7]:
# find index of eigenvalue = 1
idx = np.argmin(np.abs(eigenvalues - 1))
w = np.real(eigenvectors[:, idx]).T
# remember to normalize eigenvector to get a probability distribution
w/np.sum(w)

array([0.13888889, 0.13888889, 0.13888889, 0.13888889, 0.11111111,
       0.11111111, 0.11111111, 0.11111111])

In [8]:
A = P.T - np.eye(8)
A[7] = [1,1,1,1,1,1,1,1]
K = np.linalg.solve(A, [0,0,0,0,0,0,0,1])

In [9]:
K

array([0.13888889, 0.13888889, 0.13888889, 0.13888889, 0.11111111,
       0.11111111, 0.11111111, 0.11111111])

In [48]:
def prob_dist (m):
    matrix_len = len(m)
    P = m/np.sum(m, 1)[:, np.newaxis]
    print (P)
    eigenvalues, eigenvectors = np.linalg.eig(P.T)
    idx = np.argmin(np.abs(eigenvalues - 1))
    w = np.real(eigenvectors[:, idx]).T
    # remember to normalize eigenvector to get a probability distribution
    w/np.sum(w)
    A = P.T - np.eye(matrix_len)
    A[7] = [1 for i in range(matrix_len)]
    R = [0 for i in range(matrix_len)]
    R[matrix_len-1] = 1
    K = np.linalg.solve(A, R)
    return K

In [49]:
prob_dist(m)

[[0.   0.2  0.2  0.2  0.2  0.   0.2  0.  ]
 [0.2  0.   0.2  0.2  0.   0.2  0.   0.2 ]
 [0.2  0.2  0.   0.2  0.   0.2  0.2  0.  ]
 [0.2  0.2  0.2  0.   0.2  0.   0.   0.2 ]
 [0.25 0.   0.   0.25 0.   0.   0.25 0.25]
 [0.   0.25 0.25 0.   0.   0.   0.25 0.25]
 [0.25 0.   0.25 0.   0.25 0.25 0.   0.  ]
 [0.   0.25 0.   0.25 0.25 0.25 0.   0.  ]]


array([0.13888889, 0.13888889, 0.13888889, 0.13888889, 0.11111111,
       0.11111111, 0.11111111, 0.11111111])

In [102]:
L = np.array([[1.7, -0.9, -0.7, 0, 0, -0.1],
              [-0.9, 1.7, -0.8, 0, 0, 0],
              [-0.7, -0.8, 1.7, -0.2, 0, 0],
              [0, 0, -0.2, 1.6, -0.6, -0.8],
              [0, 0, 0, -0.6, 1.3, -0.7],
              [-0.1, 0, 0, -0.8, -0.7, 1.6]])

In [103]:
L

array([[ 1.7, -0.9, -0.7,  0. ,  0. , -0.1],
       [-0.9,  1.7, -0.8,  0. ,  0. ,  0. ],
       [-0.7, -0.8,  1.7, -0.2,  0. ,  0. ],
       [ 0. ,  0. , -0.2,  1.6, -0.6, -0.8],
       [ 0. ,  0. ,  0. , -0.6,  1.3, -0.7],
       [-0.1,  0. ,  0. , -0.8, -0.7,  1.6]])

In [53]:
eigenvalues, eigenvectors = np.linalg.eig(L)

In [110]:
evals, evecs = np.linalg.eig(L.T)


In [111]:
stationary = np.array(evecs[:,np.where(np.abs(evals-1.) < 1e-8)[0][0]].flat)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [55]:
eigenvectors

array([[-0.40824829, -0.4079592 , -0.08635251, -0.42850179,  0.60136076,
        -0.33793094],
       [-0.40824829, -0.44011885, -0.10935762, -0.09753036, -0.76437314,
        -0.18409554],
       [-0.40824829, -0.37308899,  0.13586301,  0.55011991,  0.20463384,
         0.57547567],
       [-0.40824829,  0.36703907,  0.54726317,  0.35441181,  0.00912731,
        -0.52290309],
       [-0.40824829,  0.45139833, -0.7651681 ,  0.20254316,  0.04829003,
        -0.02711092],
       [-0.40824829,  0.40272964,  0.27775205, -0.58104274, -0.09903881,
         0.49656482]])

In [66]:
k = np.array([[1.7, 0.9, 0.7, 0, 0, 0.1],
              [0.9, 1.7, 0.8, 0, 0, 0],
              [0.7, 0.8, 1.7, 0.2, 0, 0],
              [0, 0, 0.2, 1,6, 0.6, 0.8],
              [0, 0, 0, 0.6, 1.3, 0.7],
              [0.1, 0, 0, 0.8, 0.7, 1.6]])

In [67]:
k

array([list([1.7, 0.9, 0.7, 0, 0, 0.1]), list([0.9, 1.7, 0.8, 0, 0, 0]),
       list([0.7, 0.8, 1.7, 0.2, 0, 0]),
       list([0, 0, 0.2, 1, 6, 0.6, 0.8]), list([0, 0, 0, 0.6, 1.3, 0.7]),
       list([0.1, 0, 0, 0.8, 0.7, 1.6])], dtype=object)

In [98]:
eigenvalues, eigenvectors = np.linalg.eig(m)

In [99]:
m = np.array([
              [1.7, 0.9, 0.7, 0, 0, 0.1],
              [0.9, 1.7, 0.8, 0, 0, 0],
              [0.7, 0.8, 1.7, 0.2, 0, 0],
              [0, 0, 0.2, 1.6, 0.6, 0.8],
              [0, 0, 0, 0.6, 1.3, 0.7],
              [0.1, 0, 0, 0.8, 0.7, 1.6]
             ])

In [100]:
m

array([[1.7, 0.9, 0.7, 0. , 0. , 0.1],
       [0.9, 1.7, 0.8, 0. , 0. , 0. ],
       [0.7, 0.8, 1.7, 0.2, 0. , 0. ],
       [0. , 0. , 0.2, 1.6, 0.6, 0.8],
       [0. , 0. , 0. , 0.6, 1.3, 0.7],
       [0.1, 0. , 0. , 0.8, 0.7, 1.6]])

In [101]:
eigenvalues, eigenvectors

(array([3.33090457, 2.89958529, 1.1042633 , 0.69183467, 0.81529205,
        0.75812012]),
 array([[-0.55967448, -0.14260747,  0.49303669,  0.33176432, -0.5222815 ,
          0.20123834],
        [-0.57516354, -0.17644887,  0.17497377, -0.1545908 ,  0.51363101,
         -0.56543943],
        [-0.54291227, -0.10414843, -0.68496415, -0.17841851,  0.0195499 ,
          0.4393269 ],
        [-0.16767563,  0.58024696, -0.38523211,  0.35656483, -0.31301851,
         -0.51154228],
        [-0.10154817,  0.48300933,  0.16956473,  0.45908798,  0.58801334,
          0.41366206],
        [-0.15089894,  0.60638063,  0.28278461, -0.70448613, -0.13886234,
          0.11824317]]))

In [83]:
P = np.array([[0, 0.5294, 0.4118, 0, 0, 0.0588],
              [0.5294, 0, 0.4706, 0, 0, 0],
              [0.4118, 0.4706, 0, 0.1176, 0, 0],
              [0, 0, 0.1250, 0, 0.3750, 0.5],
              [0, 0, 0, 0.4615, 0, 0.5385],
              [0.0625, 0, 0, 0.5, 0.4375, 0]
    
])

In [84]:
eigenvalues, eigenvectors = np.linalg.eig(P)

In [85]:
eigenvalues, eigenvectors

(array([ 1.        ,  0.88149332, -0.33004827, -0.4434752 , -0.56510325,
        -0.5428666 ]),
 array([[ 0.40824829,  0.38060153, -0.41947971, -0.32527895,  0.44503828,
          0.38338984],
        [ 0.40824829,  0.4129847 , -0.17931934,  0.11259728, -0.20981723,
         -0.73356274],
        [ 0.40824829,  0.34541606,  0.59765533,  0.25981422, -0.24869287,
          0.4149174 ],
        [ 0.40824829, -0.39626152,  0.50913535, -0.29132291,  0.4762787 ,
         -0.32236484],
        [ 0.40824829, -0.47112913, -0.3585646 ,  0.76465656,  0.22693316,
          0.11621882],
        [ 0.40824829, -0.43161094, -0.21656887, -0.38005701, -0.64631994,
          0.15910874]]))

In [89]:
from scipy.linalg import eig

In [90]:
P = np.array([[0, 1/3, 1/3, 0, 0, 1/3],
              [1/2, 0, 1/2, 0, 0, 0],
              [1/3, 1/3, 0, 1/3, 0, 0],
              [0, 0, 1/3, 0, 1/3, 1/3],
              [0 ,0 , 0, 1/2, 0, 1/2],
              [1/3, 0 , 0, 1/3, 1/3 , 0]
             ])

In [92]:
w, vl, vr = eig(P, left=True)

In [93]:
w

array([ 1.00000000e+00+0.j,  5.77350269e-01+0.j, -3.77440267e-17+0.j,
       -3.33333333e-01+0.j, -6.66666667e-01+0.j, -5.77350269e-01+0.j])

In [94]:
vl

array([[ 4.52267017e-01,  3.87298335e-01,  5.00000000e-01,
        -2.88675135e-01,  5.00000000e-01, -3.87298335e-01],
       [ 3.01511345e-01,  4.47213595e-01, -1.99496301e-16,
         5.77350269e-01, -6.81418003e-16,  4.47213595e-01],
       [ 4.52267017e-01,  3.87298335e-01, -5.00000000e-01,
        -2.88675135e-01, -5.00000000e-01, -3.87298335e-01],
       [ 4.52267017e-01, -3.87298335e-01, -5.00000000e-01,
        -2.88675135e-01,  5.00000000e-01,  3.87298335e-01],
       [ 3.01511345e-01, -4.47213595e-01, -1.00129759e-16,
         5.77350269e-01, -4.25335575e-16, -4.47213595e-01],
       [ 4.52267017e-01, -3.87298335e-01,  5.00000000e-01,
        -2.88675135e-01, -5.00000000e-01,  3.87298335e-01]])

In [95]:
vr

array([[ 4.08248290e-01,  3.16227766e-01,  5.00000000e-01,
        -2.13200716e-01,  5.00000000e-01, -3.16227766e-01],
       [ 4.08248290e-01,  5.47722558e-01,  9.39435739e-18,
         6.39602149e-01, -1.36780033e-15,  5.47722558e-01],
       [ 4.08248290e-01,  3.16227766e-01, -5.00000000e-01,
        -2.13200716e-01, -5.00000000e-01, -3.16227766e-01],
       [ 4.08248290e-01, -3.16227766e-01, -5.00000000e-01,
        -2.13200716e-01,  5.00000000e-01,  3.16227766e-01],
       [ 4.08248290e-01, -5.47722558e-01, -3.45826423e-17,
         6.39602149e-01, -2.26079817e-16, -5.47722558e-01],
       [ 4.08248290e-01, -3.16227766e-01,  5.00000000e-01,
        -2.13200716e-01, -5.00000000e-01,  3.16227766e-01]])